language: java
jdk:
  - openjdk8
sudo: false
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
install: skip
test: skip
jobs:
  include:
    - stage: build master
      script: "./gradlew spotlessCheck check jacocoTestReport"
      if: branch = master OR type = pull_request
    - stage: release github
      if: branch =~ /release/
      script: "./gradlew check distZip distTar -Pversion=${TRAVIS_BRANCH#'release/'}
      && ./scripts/github-release.sh"
env:
  global:
    secure: pMYc0iOqjntOyM2coYOrsuDfqm+2Ho60TqMZ+Jx6M7KpuHCwvi6dv3X4GGGTcLJIIfdGPoCHPYx6balDMUDQ88tiuSHb2v5zQx3hPMO32T9F4xaxJghslJN2zo2TUiqOaurWXtUN9o7L34vZFN8yt4GvwwwHXz39+KrGm7RIr44+hPUOgc8+FUYr0Xx76d//mhuY7UyNCOed6aWuaE/clMA3kBflcDwWQYzMOCyLnPAeY9zagAp+QM1wMXVqqliviM8Qjjr3Ac9TScZLsedxNiX7jIz6KLgw+ZV5bEk0cEjr08PQLYVFW7lbRpz53jyCfDMCrDc0ImnUfNMqUcYIqh6trn8mAO5Vafb7DXXbj7ceRbYu5+3hK3cMUMIHgDEHhwC5u1LlkajyX7NHURX7H8rDsz26jU/sViz9xrjgq/xdRfCNbg/kvn7GkSxgoFfkOFcueYGBV+SnigmAD7ZNm9eFQq3edXH0vzr/VndiD/DMicRb6EPCNhQgAJfr//dy8TpTFFz9r/DR2xsnONoZr1igM6v87LQKLWf6UVMCRMNfh0I/30LhNUJDUidFkzmpUl7cdQS2PR+2oL3rk2ec6M9bun/6NYMI7hf7mRbbI24SYJEEcSvhYcfnPlQvTMV1jZTChgFyW8m4sy6wZvymVSCY40Milxw8a9iocpwgyzk=